//AUTOGENERATED FILE FROM png2asset
// Conversion args: \BallSprite.png -spr8x8

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(BallSprite)

const palette_color_t BallSprite_palettes[4] = {
	RGB8(255,255,255), RGB8(168,168,168), RGB8( 96, 96, 96), RGB8(  0,  0,  0)
	};

const uint8_t BallSprite_tiles[16] = {
	0x3c,0x3c,0x3c,0x66,0xff,0xff,0xff,0xbd,0xff,0xbd,0xff,0xff,0x3c,0x66,0x3c,0x3c
	};

const metasprite_t BallSprite_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const BallSprite_metasprites[1] = {
	BallSprite_metasprite0
};
