//AUTOGENERATED FILE FROM png2asset
// Conversion args: \BallSprite.png -spr8x8

#ifndef METASPRITE_BallSprite_H
#define METASPRITE_BallSprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define BallSprite_TILE_ORIGIN 0
#define BallSprite_TILE_W 8
#define BallSprite_TILE_H 8
#define BallSprite_WIDTH 8
#define BallSprite_HEIGHT 8
#define BallSprite_TILE_COUNT 1
#define BallSprite_PALETTE_COUNT 1
#define BallSprite_COLORS_PER_PALETTE 4
#define BallSprite_TOTAL_COLORS 4
#define BallSprite_PIVOT_X 4
#define BallSprite_PIVOT_Y 4
#define BallSprite_PIVOT_W 8
#define BallSprite_PIVOT_H 8
extern const metasprite_t* const BallSprite_metasprites[1];

BANKREF_EXTERN(BallSprite)

extern const palette_color_t BallSprite_palettes[4];
extern const uint8_t BallSprite_tiles[16];

#endif
